{
 "title": "LinkitAir",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests to FlightsController",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri=~\"/flights/.*\"})"
    }
   ]
  },
  {
   "title": "HTTP Response Codes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{status=~\"200\"}) by (code)",
     "legendFormat": "200"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{status=~\"4.*\"})",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{status=~\"5.*\"})",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Response Times (ms)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(http_server_requests_seconds_sum / http_server_requests_seconds_count) * 1000",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(http_server_requests_seconds_sum / http_server_requests_seconds_count) * 1000",
     "legendFormat": "Avg"
    },
    {
     "expr": "min(http_server_requests_seconds_sum / http_server_requests_seconds_count) * 1000",
     "legendFormat": "Min"
    }
   ]
  }
 ]
}